# Bluetooth Configurations
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="BLE_Beacon"   # Gives human readable name to identify during scan
CONFIG_BT_OBSERVER=y    # Required for BLE scan
CONFIG_SETTINGS=y
# Hardware Drivers
CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_PRINTK=y
#CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_BT_IAS=y

# Fundamental Memory Fixes
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# Bluetooth Stack Sizes
CONFIG_BT_RX_STACK_SIZE=4096

# Balanced Buffers --> Reduced from 255 to 76 to save Heap
CONFIG_BT_BUF_ACL_RX_SIZE=76
CONFIG_BT_BUF_ACL_TX_SIZE=76
CONFIG_BT_L2CAP_TX_MTU=65
CONFIG_BT_BUF_CMD_TX_SIZE=76

# Floating Point Access
CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# RSSI of the connected device
#CONFIG_BT_CTLR_CONN_RSSI=y

CONFIG_BT_CTLR=y
CONFIG_BT_LL_SW_SPLIT=y

# Authentication configurations
CONFIG_BT_SMP=y
CONFIG_BT_SETTINGS=y
#CONFIG_BT_FIXED_PASSKEY=y

# Watchdog configurations
CONFIG_WDT_LOG_LEVEL_DBG=y
CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=n
